apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: canteen-app
data:
  # The API URL should be your ingress hostname without the /api path
  api_url: http://localhost:30001
  # Replace APP_HOSTNAME with the hostname you'll use for your application
  app_hostname: APP_HOSTNAME
